global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: odoo-connect
  tag: latest

config:
  TZ: ""
  IS_ODOO_16: true
  ODOO_DB_HOST: ""
  OPENMRS_HOST: ""
  OPENMRS_PORT: ""
  OPENELIS_HOST: ""
  OPENELIS_PORT: ""
  ODOO_HOST: ""
  ODOO_PORT: ""
  ODOO_DB_NAME: ""
    
secrets:
  ODOO_DB_USERNAME: ""
  ODOO_DB_PASSWORD: ""
  OPENMRS_ATOMFEED_USER: ""
  OPENMRS_ATOMFEED_PASSWORD: ""
  OPENELIS_ATOMFEED_USER: ""
  OPENELIS_ATOMFEED_PASSWORD: ""
  ODOO_ATOMFEED_USER: ""
  ODOO_ATOMFEED_PASSWORD: ""


autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}
