apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  TZ: "{{ .Values.global.TZ }}"
  IS_ODOO_16: "{{ .Values.config.IS_ODOO_16 }}"
  ODOO_DB_NAME: "{{ .Values.config.ODOO_DB_NAME }}"
  ODOO_DB_SERVER: "{{ .Values.config.ODOO_DB_HOST }}"
  OPENMRS_HOST: "{{ .Values.config.OPENMRS_HOST }}"
  OPENMRS_PORT: "{{ .Values.config.OPENMRS_PORT }}"
  OPENELIS_HOST: "{{ .Values.config.OPENELIS_HOST }}"
  OPENELIS_PORT: "{{ .Values.config.OPENELIS_PORT }}"
  ODOO_HOST: "{{ .Values.config.ODOO_HOST }}"
  ODOO_PORT: "{{ .Values.config.ODOO_PORT }}"
  BILLING_EXEMPT_ATTRIBUTE_NAME: "{{ .Values.config.BILLING_EXEMPT_ATTRIBUTE_NAME }}"
  
