apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  ODOO_DB_USERNAME: {{ .Values.secrets.ODOO_DB_USERNAME | b64enc | quote }}
  ODOO_DB_PASSWORD: {{ .Values.secrets.ODOO_DB_PASSWORD | b64enc | quote}}
  OPENMRS_ATOMFEED_USER: {{ .Values.secrets.OPENMRS_ATOMFEED_USER | b64enc | quote }}
  OPENMRS_ATOMFEED_PASSWORD: {{ .Values.secrets.OPENMRS_ATOMFEED_PASSWORD | b64enc | quote}}
  OPENELIS_ATOMFEED_USER: {{ .Values.secrets.OPENELIS_ATOMFEED_USER | b64enc | quote }}
  OPENELIS_ATOMFEED_PASSWORD: {{ .Values.secrets.OPENELIS_ATOMFEED_PASSWORD | b64enc | quote}}
  ODOO_ATOMFEED_USER: {{ .Values.secrets.ODOO_ATOMFEED_USER | b64enc | quote }}
  ODOO_ATOMFEED_PASSWORD: {{ .Values.secrets.ODOO_ATOMFEED_PASSWORD | b64enc | quote}}
  
